In [12]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name": [
        "Ram", "Shyam", "Hari", "Sita", "Gita",
        "Nabin", "Rita", "Bikash", "Anita", "Suman",
        "Roshan", "Puja", "Aashish", "Kiran", "Prabin",
        "Sarita", "Dipak", "Manisha", "Ramesh", "Nisha"
    ],

    "Developer": [
        "Frontend", "Backend", "Database", "ML", "Frontend",
        "Backend", "ML", "Database", "Frontend", "Backend",
        "ML", "Database", "Frontend", "ML", "Backend",
        "Database", "ML", "Frontend", "Backend", "Database"
    ],

    "Salary": [
        55000, np.nan, 75000, 90000, np.nan,
        72000, 95000, np.nan, 52000, 68000,
        np.nan, 78000, 65000, np.nan, 71000,
        83000, 88000, np.nan, 69000, 85000
    ]
})
df

       Name Developer   Salary
0       Ram  Frontend  55000.0
1     Shyam   Backend      NaN
2      Hari  Database  75000.0
3      Sita        ML  90000.0
4      Gita  Frontend      NaN
5     Nabin   Backend  72000.0
6      Rita        ML  95000.0
7    Bikash  Database      NaN
8     Anita  Frontend  52000.0
9     Suman   Backend  68000.0
10   Roshan        ML      NaN
11     Puja  Database  78000.0
12  Aashish  Frontend  65000.0
13    Kiran        ML      NaN
14   Prabin   Backend  71000.0
15   Sarita  Database  83000.0
16    Dipak        ML  88000.0
17  Manisha  Frontend      NaN
18   Ramesh   Backend  69000.0
19    Nisha  Database  85000.0

In [13]:
df["Average"]=df.groupby("Developer")["Salary"].transform("mean")
df["Salary"]= df["Salary"].fillna(df["Average"])
df

       Name Developer        Salary       Average
0       Ram  Frontend  55000.000000  57333.333333
1     Shyam   Backend  70000.000000  70000.000000
2      Hari  Database  75000.000000  80250.000000
3      Sita        ML  90000.000000  91000.000000
4      Gita  Frontend  57333.333333  57333.333333
5     Nabin   Backend  72000.000000  70000.000000
6      Rita        ML  95000.000000  91000.000000
7    Bikash  Database  80250.000000  80250.000000
8     Anita  Frontend  52000.000000  57333.333333
9     Suman   Backend  68000.000000  70000.000000
10   Roshan        ML  91000.000000  91000.000000
11     Puja  Database  78000.000000  80250.000000
12  Aashish  Frontend  65000.000000  57333.333333
13    Kiran        ML  91000.000000  91000.000000
14   Prabin   Backend  71000.000000  70000.000000
15   Sarita  Database  83000.000000  80250.000000
16    Dipak        ML  88000.000000  91000.000000
17  Manisha  Frontend  57333.333333  57333.333333
18   Ramesh   Backend  69000.000000  70000.000000
19    Nisha  Database  85000.000000  80250.000000