In [ ]:

#Outliers affects minmax

# Min = 0 and Max = 1

import pandas as pd


df = pd.DataFrame({
    "Study Hours": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Age": [18, 19, 18, 20, 21, 19, 22, 20, 21, 23],
    "Result": [
        "Fail", "Fail", "Fail", "Pass", "Pass",
        "Pass", "Pass", "Pass", "Pass", "Pass"
    ]
})


df

   Study Hours  Age Result
0            1   18   Fail
1            2   19   Fail
2            3   18   Fail
3            4   20   Pass
4            5   21   Pass
5            6   19   Pass
6            7   22   Pass
7            8   20   Pass
8            9   21   Pass
9           10   23   Pass

In [11]:
from sklearn.preprocessing import MinMaxScaler


feature = ["Study Hours", "Age"]

scaler = MinMaxScaler()

scaled_feature = scaler.fit_transform(df[feature])


df[scaler.get_feature_names_out()] = scaled_feature
df

   Study Hours  Age Result
0     0.000000  0.0   Fail
1     0.111111  0.2   Fail
2     0.222222  0.0   Fail
3     0.333333  0.4   Pass
4     0.444444  0.6   Pass
5     0.555556  0.2   Pass
6     0.666667  0.8   Pass
7     0.777778  0.4   Pass
8     0.888889  0.6   Pass
9     1.000000  1.0   Pass